### ISSUE TITLE
Fix CSS selectors

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Christian#5]
Some CSS selectors should be revised:
- [ ] Problem Selector: "\* html #footer"
- [ ] Overly Prescriptive Selector: "body, html"
## Problem Selector: "\* html #footer"

The CSS selector **\* html #footer** will not work because it's looking for an html tag that is **inside** of _any_ element *****.  This rule could just be simplified to: **#footer**.

``` css
/* 2 column1socialmedia.html */
    * html #footer {
        height:1px;
    }
```
## Overly Prescriptive Selector: "body, html"

The following selector is applying its rules to both the **html** tags and **body** tags:

``` css
/* 2 column1socialmedia.html */
        body,
    html {
        margin:0;
        padding:0;
        color:#000;
        background:#a7a09a;
    }
```

Because the **html** tag is our document root tag and not a visible element on the page, we won't be applying things like margin, padding, and background on it.  We'd instead do that only for visible tags _inside_ the **html** tag.
